// <auto-generated />
using Infrastructure.Data;
using Infrastructure.Data.CompiledModels;
using Microsoft.EntityFrameworkCore.Infrastructure;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(ApplicationContext), typeof(ApplicationContextModel))]
