// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Infrastructure.Data.CompiledModels
{
    public partial class ApplicationContextModel
    {
        private ApplicationContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("3f24d24e-777f-422b-a39d-607a5555def1"), entityTypeCount: 7)
        {
        }

        partial void Initialize()
        {
            var user = UserEntityType.Create(this);
            var deviceId = DeviceIdEntityType.Create(this);
            var email = EmailEntityType.Create(this);
            var emailVerificationCode = EmailVerificationCodeEntityType.Create(this);
            var password = PasswordEntityType.Create(this);
            var passwordResetToken = PasswordResetTokenEntityType.Create(this);
            var refreshToken = RefreshTokenEntityType.Create(this);

            DeviceIdEntityType.CreateForeignKey1(deviceId, refreshToken);
            EmailEntityType.CreateForeignKey1(email, user);
            EmailVerificationCodeEntityType.CreateForeignKey1(emailVerificationCode, user);
            PasswordEntityType.CreateForeignKey1(password, user);
            PasswordResetTokenEntityType.CreateForeignKey1(passwordResetToken, user);
            RefreshTokenEntityType.CreateForeignKey1(refreshToken, user);

            UserEntityType.CreateAnnotations(user);
            DeviceIdEntityType.CreateAnnotations(deviceId);
            EmailEntityType.CreateAnnotations(email);
            EmailVerificationCodeEntityType.CreateAnnotations(emailVerificationCode);
            PasswordEntityType.CreateAnnotations(password);
            PasswordResetTokenEntityType.CreateAnnotations(passwordResetToken);
            RefreshTokenEntityType.CreateAnnotations(refreshToken);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "9.0.4");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
