FROM mcr.microsoft.com/dotnet/sdk:9.0 AS tool-runner
WORKDIR /src

RUN dotnet tool install --global dotnet-ef

ENV PATH="$PATH:/root/.dotnet/tools"
ENV ASPNETCORE_ENVIRONMENT=Production

COPY . .

ENTRYPOINT ["dotnet-ef"]