// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Infrastructure.Data.CompiledModels
{
    public partial class ApplicationContextModel
    {
        private ApplicationContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("1781c97c-cd7e-448d-8771-254618d53ade"), entityTypeCount: 5)
        {
        }

        partial void Initialize()
        {
            var chat = ChatEntityType.Create(this);
            var message = MessageEntityType.Create(this);
            var sender = SenderEntityType.Create(this);
            var subscription = SubscriptionEntityType.Create(this);
            var user = UserEntityType.Create(this);

            ChatEntityType.CreateForeignKey1(chat, user);
            MessageEntityType.CreateForeignKey1(message, chat);
            SenderEntityType.CreateForeignKey1(sender, message);
            UserEntityType.CreateForeignKey1(user, subscription);

            ChatEntityType.CreateAnnotations(chat);
            MessageEntityType.CreateAnnotations(message);
            SenderEntityType.CreateAnnotations(sender);
            SubscriptionEntityType.CreateAnnotations(subscription);
            UserEntityType.CreateAnnotations(user);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "9.0.4");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
