name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  HELM_COMMAND: helm upgrade netiq netiq-k8s --values netiq-k8s/values.yaml --install --atomic --wait
  DOCKER_REPO: netiq
  DOCKER_USERNAME: jasonstathamdev

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: client
            context: ./client
            dockerfile: ./client/Dockerfile 
            tag: client
          - name: auth-app
            context: ./server 
            dockerfile: ./server/Auth/Dockerfile 
            tag: auth-app
          - name: netiq-app
            context: ./server 
            dockerfile: ./server/Backend/Dockerfile 
            tag: netiq-app

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ${{ matrix.name }} image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}:${{ matrix.tag }}
          cache-from: type=registry,ref=${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}:${{ matrix.tag }}-cache
          cache-to: type=registry,ref=${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}:${{ matrix.tag }}-cache,mode=max

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
          ssh root@${{ secrets.SERVER_IP }} "${{ env.HELM_COMMAND }}"