name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DOCKER_USERNAME: jasonstathamdev
  DOCKER_REPO: netiq
  SERVER_IP: 89.169.154.188

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

  build-client:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push client
        uses: docker/build-push-action@v2
        with:
          context: ./chatgpt-client
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}:client

  build-auth:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.0.x"

      - name: Prepare Auth migrations
        run: |
          mkdir -p chatgpt-server/Auth/migrator/Migrator/Migrations
          cp -r chatgpt-server/Auth/app/Infrastructure/Migrations/* chatgpt-server/Auth/migrator/Migrator/Migrations/

      - name: Run MigrationChanger for Auth
        run: |
          dotnet build chatgpt-server/Auth/migrator/MigrationChanger
          dotnet run --project chatgpt-server/Auth/migrator/MigrationChanger

      - name: Build and push Auth app
        uses: docker/build-push-action@v2
        with:
          context: ./chatgpt-server
          file: ./chatgpt-server/Auth/app/Dockerfile
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}:auth-app

      - name: Build and push Auth migrator
        uses: docker/build-push-action@v2
        with:
          context: ./chatgpt-server/Auth/migrator
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}:auth-migrator

  build-server:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.0.x"

      - name: Prepare Server migrations
        run: |
          mkdir -p chatgpt-server/Chatgpt/migrator/Migrator/Migrations
          cp -r chatgpt-server/Chatgpt/app/Infrastructure/Migrations/* chatgpt-server/Chatgpt/migrator/Migrator/Migrations/

      - name: Run MigrationChanger for Server
        run: |
          dotnet build chatgpt-server/Chatgpt/migrator/MigrationChanger
          dotnet run --project chatgpt-server/Chatgpt/migrator/MigrationChanger

      - name: Build and push Server app
        uses: docker/build-push-action@v2
        with:
          context: ./chatgpt-server
          file: ./chatgpt-server/Chatgpt/app/Dockerfile
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}:netiq-app

      - name: Build and push Server migrator
        uses: docker/build-push-action@v2
        with:
          context: ./chatgpt-server/Chatgpt/migrator
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}:netiq-migrator

  deploy:
    needs: [build-client, build-auth, build-server]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ env.SERVER_IP }} >> ~/.ssh/known_hosts
          ssh yegor@${{ env.SERVER_IP }} "helm upgrade netiq netiq-k8s --values netiq-k8s/values.yaml"
